/*
 * This file is generated by jOOQ.
 */
package jooq.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Line implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long   id;
    private String name;
    private String geometry;
    private Double length;

    public Line() {}

    public Line(Line value) {
        this.id = value.id;
        this.name = value.name;
        this.geometry = value.geometry;
        this.length = value.length;
    }

    public Line(
        Long   id,
        String name,
        String geometry,
        Double length
    ) {
        this.id = id;
        this.name = name;
        this.geometry = geometry;
        this.length = length;
    }

    /**
     * Getter for <code>public.line.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.line.id</code>.
     */
    public Line setId(Long id) {
        this.id = id;
        return this;
    }

    /**
     * Getter for <code>public.line.name</code>.
     */
    public String getName() {
        return this.name;
    }

    /**
     * Setter for <code>public.line.name</code>.
     */
    public Line setName(String name) {
        this.name = name;
        return this;
    }

    /**
     * Getter for <code>public.line.geometry</code>.
     */
    public String getGeometry() {
        return this.geometry;
    }

    /**
     * Setter for <code>public.line.geometry</code>.
     */
    public Line setGeometry(String geometry) {
        this.geometry = geometry;
        return this;
    }

    /**
     * Getter for <code>public.line.length</code>.
     */
    public Double getLength() {
        return this.length;
    }

    /**
     * Setter for <code>public.line.length</code>.
     */
    public Line setLength(Double length) {
        this.length = length;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Line other = (Line) obj;
        if (id == null) {
            if (other.id != null)
                return false;
        }
        else if (!id.equals(other.id))
            return false;
        if (name == null) {
            if (other.name != null)
                return false;
        }
        else if (!name.equals(other.name))
            return false;
        if (geometry == null) {
            if (other.geometry != null)
                return false;
        }
        else if (!geometry.equals(other.geometry))
            return false;
        if (length == null) {
            if (other.length != null)
                return false;
        }
        else if (!length.equals(other.length))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.name == null) ? 0 : this.name.hashCode());
        result = prime * result + ((this.geometry == null) ? 0 : this.geometry.hashCode());
        result = prime * result + ((this.length == null) ? 0 : this.length.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Line (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(geometry);
        sb.append(", ").append(length);

        sb.append(")");
        return sb.toString();
    }
}
