/*
 * This file is generated by jOOQ.
 */
package jooq.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Polygon implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long   id;
    private String name;
    private String geometry;
    private Double area;

    public Polygon() {}

    public Polygon(Polygon value) {
        this.id = value.id;
        this.name = value.name;
        this.geometry = value.geometry;
        this.area = value.area;
    }

    public Polygon(
        Long   id,
        String name,
        String geometry,
        Double area
    ) {
        this.id = id;
        this.name = name;
        this.geometry = geometry;
        this.area = area;
    }

    /**
     * Getter for <code>public.polygon.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.polygon.id</code>.
     */
    public Polygon setId(Long id) {
        this.id = id;
        return this;
    }

    /**
     * Getter for <code>public.polygon.name</code>.
     */
    public String getName() {
        return this.name;
    }

    /**
     * Setter for <code>public.polygon.name</code>.
     */
    public Polygon setName(String name) {
        this.name = name;
        return this;
    }

    /**
     * Getter for <code>public.polygon.geometry</code>.
     */
    public String getGeometry() {
        return this.geometry;
    }

    /**
     * Setter for <code>public.polygon.geometry</code>.
     */
    public Polygon setGeometry(String geometry) {
        this.geometry = geometry;
        return this;
    }

    /**
     * Getter for <code>public.polygon.area</code>.
     */
    public Double getArea() {
        return this.area;
    }

    /**
     * Setter for <code>public.polygon.area</code>.
     */
    public Polygon setArea(Double area) {
        this.area = area;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Polygon other = (Polygon) obj;
        if (id == null) {
            if (other.id != null)
                return false;
        }
        else if (!id.equals(other.id))
            return false;
        if (name == null) {
            if (other.name != null)
                return false;
        }
        else if (!name.equals(other.name))
            return false;
        if (geometry == null) {
            if (other.geometry != null)
                return false;
        }
        else if (!geometry.equals(other.geometry))
            return false;
        if (area == null) {
            if (other.area != null)
                return false;
        }
        else if (!area.equals(other.area))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.name == null) ? 0 : this.name.hashCode());
        result = prime * result + ((this.geometry == null) ? 0 : this.geometry.hashCode());
        result = prime * result + ((this.area == null) ? 0 : this.area.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Polygon (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(geometry);
        sb.append(", ").append(area);

        sb.append(")");
        return sb.toString();
    }
}
