/*
 * This file is generated by jOOQ.
 */
package jooq;


import jooq.tables.Client;
import jooq.tables.FeatureCollection;
import jooq.tables.Line;
import jooq.tables.Polygon;
import jooq.tables.Product;
import jooq.tables.records.ClientRecord;
import jooq.tables.records.FeatureCollectionRecord;
import jooq.tables.records.LineRecord;
import jooq.tables.records.PolygonRecord;
import jooq.tables.records.ProductRecord;

import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in 
 * public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<ClientRecord> CLIENT_PKEY = Internal.createUniqueKey(Client.CLIENT, DSL.name("client_pkey"), new TableField[] { Client.CLIENT.ID }, true);
    public static final UniqueKey<FeatureCollectionRecord> FEATURE_COLLECTION_PKEY = Internal.createUniqueKey(FeatureCollection.FEATURE_COLLECTION, DSL.name("feature_collection_pkey"), new TableField[] { FeatureCollection.FEATURE_COLLECTION.ID }, true);
    public static final UniqueKey<LineRecord> LINE_PKEY = Internal.createUniqueKey(Line.LINE, DSL.name("line_pkey"), new TableField[] { Line.LINE.ID }, true);
    public static final UniqueKey<PolygonRecord> POLYGON_PKEY = Internal.createUniqueKey(Polygon.POLYGON, DSL.name("polygon_pkey"), new TableField[] { Polygon.POLYGON.ID }, true);
    public static final UniqueKey<ProductRecord> PRODUCT_PKEY = Internal.createUniqueKey(Product.PRODUCT, DSL.name("product_pkey"), new TableField[] { Product.PRODUCT.ID }, true);
}
