/*
 * This file is generated by jOOQ.
 */
package jooq;


import java.util.Arrays;
import java.util.List;

import jooq.tables.Client;
import jooq.tables.FeatureCollection;
import jooq.tables.Line;
import jooq.tables.Polygon;
import jooq.tables.Product;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.client</code>.
     */
    public final Client CLIENT = Client.CLIENT;

    /**
     * The table <code>public.feature_collection</code>.
     */
    public final FeatureCollection FEATURE_COLLECTION = FeatureCollection.FEATURE_COLLECTION;

    /**
     * The table <code>public.line</code>.
     */
    public final Line LINE = Line.LINE;

    /**
     * The table <code>public.polygon</code>.
     */
    public final Polygon POLYGON = Polygon.POLYGON;

    /**
     * The table <code>public.product</code>.
     */
    public final Product PRODUCT = Product.PRODUCT;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
            Client.CLIENT,
            FeatureCollection.FEATURE_COLLECTION,
            Line.LINE,
            Polygon.POLYGON,
            Product.PRODUCT);
    }
}
