/*
 * This file is generated by jOOQ.
 */
package jooq;


import jooq.tables.Client;
import jooq.tables.FeatureCollection;
import jooq.tables.Line;
import jooq.tables.Polygon;
import jooq.tables.Product;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.client</code>.
     */
    public static final Client CLIENT = Client.CLIENT;

    /**
     * The table <code>public.feature_collection</code>.
     */
    public static final FeatureCollection FEATURE_COLLECTION = FeatureCollection.FEATURE_COLLECTION;

    /**
     * The table <code>public.line</code>.
     */
    public static final Line LINE = Line.LINE;

    /**
     * The table <code>public.polygon</code>.
     */
    public static final Polygon POLYGON = Polygon.POLYGON;

    /**
     * The table <code>public.product</code>.
     */
    public static final Product PRODUCT = Product.PRODUCT;
}
