/*
 * This file is generated by jOOQ.
 */
package jooq.tables.records;


import jooq.tables.FeatureCollection;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FeatureCollectionRecord extends UpdatableRecordImpl<FeatureCollectionRecord> implements Record2<Long, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.feature_collection.id</code>.
     */
    public FeatureCollectionRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.feature_collection.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.feature_collection.hash</code>.
     */
    public FeatureCollectionRecord setHash(Integer value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.feature_collection.hash</code>.
     */
    public Integer getHash() {
        return (Integer) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<Long, Integer> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<Long, Integer> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return FeatureCollection.FEATURE_COLLECTION.ID;
    }

    @Override
    public Field<Integer> field2() {
        return FeatureCollection.FEATURE_COLLECTION.HASH;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public Integer component2() {
        return getHash();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public Integer value2() {
        return getHash();
    }

    @Override
    public FeatureCollectionRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public FeatureCollectionRecord value2(Integer value) {
        setHash(value);
        return this;
    }

    @Override
    public FeatureCollectionRecord values(Long value1, Integer value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached FeatureCollectionRecord
     */
    public FeatureCollectionRecord() {
        super(FeatureCollection.FEATURE_COLLECTION);
    }

    /**
     * Create a detached, initialised FeatureCollectionRecord
     */
    public FeatureCollectionRecord(Long id, Integer hash) {
        super(FeatureCollection.FEATURE_COLLECTION);

        setId(id);
        setHash(hash);
    }
}
