/*
 * This file is generated by jOOQ.
 */
package jooq.tables.records;


import jooq.tables.Polygon;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PolygonRecord extends UpdatableRecordImpl<PolygonRecord> implements Record4<Long, String, String, Double> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.polygon.id</code>.
     */
    public PolygonRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.polygon.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.polygon.name</code>.
     */
    public PolygonRecord setName(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.polygon.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.polygon.geometry</code>.
     */
    public PolygonRecord setGeometry(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.polygon.geometry</code>.
     */
    public String getGeometry() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.polygon.area</code>.
     */
    public PolygonRecord setArea(Double value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.polygon.area</code>.
     */
    public Double getArea() {
        return (Double) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<Long, String, String, Double> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<Long, String, String, Double> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return Polygon.POLYGON.ID;
    }

    @Override
    public Field<String> field2() {
        return Polygon.POLYGON.NAME;
    }

    @Override
    public Field<String> field3() {
        return Polygon.POLYGON.GEOMETRY;
    }

    @Override
    public Field<Double> field4() {
        return Polygon.POLYGON.AREA;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public String component3() {
        return getGeometry();
    }

    @Override
    public Double component4() {
        return getArea();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public String value3() {
        return getGeometry();
    }

    @Override
    public Double value4() {
        return getArea();
    }

    @Override
    public PolygonRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public PolygonRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public PolygonRecord value3(String value) {
        setGeometry(value);
        return this;
    }

    @Override
    public PolygonRecord value4(Double value) {
        setArea(value);
        return this;
    }

    @Override
    public PolygonRecord values(Long value1, String value2, String value3, Double value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PolygonRecord
     */
    public PolygonRecord() {
        super(Polygon.POLYGON);
    }

    /**
     * Create a detached, initialised PolygonRecord
     */
    public PolygonRecord(Long id, String name, String geometry, Double area) {
        super(Polygon.POLYGON);

        setId(id);
        setName(name);
        setGeometry(geometry);
        setArea(area);
    }
}
